import logging
from services.status import get_daily_telemetry
from services.notifications import send_telegram_message

logger = logging.getLogger(__name__)

def send_daily_board_report():
    """
    Fetches 24-hour fermentation progress and sends a structured report to the Board (Telegram).
    Fulfills Sprint D requirements.
    """
    try:
        telemetry = get_daily_telemetry()
        
        if "error" in telemetry:
            logger.info(f"Daily report skipped: {telemetry['error']}")
            return {"status": "skipped", "reason": telemetry['error']}
            
        batch = telemetry['batch_name']
        sg_now = telemetry['sg_now']
        sg_diff = telemetry['sg_diff']
        abv_gain = telemetry['abv_gain']
        total_abv = telemetry['total_abv']
        temp_range = telemetry['temp_range']
        pred_fg = telemetry['predicted_fg']
        pred_date = telemetry['predicted_date']
        
        # Build Message
        msg = (
            f"📈 *Daily Fermentation Report*\n"
            f"Batch: *{batch}*\n"
            f"Status: {std_status(sg_diff)}\n\n"
            f"📍 *Gravity:* {sg_now:.3f} ({format_diff(sg_diff)})\n"
            f"🍷 *ABV:* {total_abv}% (+{abv_gain}% in 24h)\n"
            f"🌡️ *Temp:* {temp_range} (Stable: {'✅' if telemetry['is_stable'] else '⚠️'})\n\n"
            f"🔮 *Forecast:* Target {pred_fg:.3f} by {pred_date}\n\n"
            f"_Generated by Brew Brain Board Scheduler_"
        )
        
        send_telegram_message(msg, force=True)
        logger.info(f"Daily Board Report sent for {batch}")
        return {"status": "success", "batch": batch}
        
    except Exception as e:
        logger.error(f"Failed to send daily report: {e}")
        return {"status": "error", "message": str(e)}

def std_status(diff):
    if diff > 0.008: return "🚀 Active Fermentation"
    if diff > 0.002: return "🐢 Slowing Down"
    if diff > -0.001 and diff < 0.001: return "🏁 Near Completion"
    return "⏸️ Idle / Equilibrium"

def format_diff(diff):
    if diff > 0: return f"-{diff:.3f}"
    if diff < 0: return f"+{abs(diff):.3f}"
    return "0.000"
