from flask import Blueprint, render_template_string
from core.config import get_config
import datetime

labels_bp = Blueprint('labels', __name__)

@labels_bp.route('', methods=['GET'])
@labels_bp.route('/', methods=['GET'])
def generate_label():
    """Generates a printable HTML keg label for the active batch."""
    config = get_config()
    batch_name = config.get("batch_name", "Unknown Brew")
    og = config.get("original_gravity", 1.050)
    fg = config.get("current_gravity", 1.010)
    abv = round((og - fg) * 131.25, 1) if og and fg else 0.0
    date_brewed = config.get("date_brewed", datetime.datetime.now().strftime("%Y-%m-%d"))
    yeast = config.get("yeast_strain", "Unknown")
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Keg Label - {batch_name}</title>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap');
            body {{
                margin: 0; padding: 20px; font-family: 'Inter', sans-serif;
                background-color: #fff; color: #000;
                display: flex; justify-content: center;
            }}
            .label {{
                width: 4in; height: 3in; border: 4px solid #000; border-radius: 12px;
                padding: 20px; box-sizing: border-box; text-align: center;
                display: flex; flex-direction: column; justify-content: space-between;
            }}
            .header {{ font-size: 14px; text-transform: uppercase; letter-spacing: 2px; font-weight: 700; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 10px; }}
            .name {{ font-size: 36px; font-weight: 900; line-height: 1.1; margin: 0; }}
            .stats {{ display: flex; justify-content: space-around; margin: 15px 0; font-size: 24px; font-weight: 700; }}
            .details {{ font-size: 12px; text-align: left; line-height: 1.5; }}
            .footer {{ font-size: 10px; color: #666; margin-top: auto; border-top: 1px solid #ccc; padding-top: 5px; }}
        </style>
    </head>
    <body onload="window.print()">
        <div class="label">
            <div class="header">Brew Brain</div>
            <h1 class="name">{batch_name}</h1>
            <div class="stats">
                <div>ABV: {abv}%</div>
                <div>FG: {fg:.3f}</div>
            </div>
            <div class="details">
                <strong>Brewed:</strong> {date_brewed}<br>
                <strong>Yeast:</strong> {yeast}
            </div>
            <div class="footer">Generated by Brew Brain Automation</div>
        </div>
    </body>
    </html>
    """
    return render_template_string(html)
